obstacle_range: 2.5
raytrace_range: 3.0
#robot_radius: 0.32
footprint: [[0.3,0.25], [0.3,0], [0.3,-0.25],[-0.3,-0.25],[-0.3,0.25]]

max_obstacle_height: 0.6
min_obstacle_height: 0.0

obstacle_layer:
  observation_sources: laser_scan_sensor
  laser_scan_sensor:
    data_type: LaserScan
    topic: scan 
    marking: true
    clearing: true
    expected_update_rate: 0

range_sensor_layer:
  topics: ["/ultrasound0", "/ultrasound3", "/ultrasound4"]
  no_readings_timeout: 0.0
  clear_threshold: 0.01
  mark_threshold: 0.1
  clear_on_max_reading: true
